import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import MainHeader from "@/components/ui/MainHeader";
import { ThemeProvider } from "@/components/theme-provider";
import { SessionProvider } from "next-auth/react";
import { ReduxProvider } from "@/components/ReduxProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "HarvestBridge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>
      <html lang="en">
        <head />
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased flex items-center justify-center`}
        >
          <ReduxProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <main className="container min-h-screen flex flex-col p-1">
                {/* Fixed header on mobile, static on desktop */}
                <header className="fixed sm:static top-0 left-0 right-0 z-50 border sm:px-4 lg:px-4 py-2 w-full p-2 sm:p-4 flex flex-col gap-6 bg-background rounded-lg">
                  <MainHeader />
                </header>

                {/* Main content with padding-top on mobile to account for fixed header */}
                <section className="flex-1 w-full mt-[88px] sm:mt-2 h-[calc(80vh-theme(spacing.24))] sm:h-[calc(80vh-theme(spacing.28))] overflow-auto flex items-center justify-center">
                  {children}
                </section>
              </main>
            </ThemeProvider>
          </ReduxProvider>
        </body>
      </html>
    </SessionProvider>
  );
}
